### ISSUE TITLE
command line args not working as expected

### ISSUE THREAD

**Issue by daveajones** [Podcastindex-org/podping.cloud#43]
The way I understand it, if I type this:

`python3 ./hive-watcher.py --old=6`

...I should see all the urls from the past 6 hours and then it will being to monitor live.  That doesn't happen though.  It just goes straight to monitoring live.

**Comment by brianoflondon** [comment]
No = just a space between --old and the number.

**Comment by stevencrader** [comment]
It will work with = too. 

The issue is that it only gets 1 post. It is breaking out because `post_time > stop_at` on line 436

**Comment by brianoflondon** [comment]
I'm trying it now...

**Comment by brianoflondon** [comment]
you're right I was dumb.

My fix does now have a Year 3333 problem though...
stop_at = datetime(year=3333, month=1, day=1)
